# Generated by Django 3.2.5 on 2021-07-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newbooks', models.IntegerField()),
                ('oldbooks', models.IntegerField()),
                ('listofbooks', models.IntegerField()),
            ],
        ),
    ]
