# Generated by Django 3.2.5 on 2021-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0003_listofbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmenu',
            name='newbooks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booksmenu',
            name='oldbooks',
            field=models.CharField(max_length=50),
        ),
    ]
