# Generated by Django 3.2.5 on 2021-07-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0004_auto_20210707_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmenu',
            name='listofbooks',
        ),
    ]
