# Generated by Django 3.2.5 on 2021-07-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0005_remove_booksmenu_listofbooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='listofbooks',
        ),
        migrations.DeleteModel(
            name='newbooks',
        ),
        migrations.DeleteModel(
            name='oldbooks',
        ),
    ]
