# Generated by Django 3.2.5 on 2021-07-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0009_ob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nb',
        ),
        migrations.DeleteModel(
            name='Ob',
        ),
    ]
