# Generated by Django 3.2.5 on 2021-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0010_auto_20210708_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=2001),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(default='', max_length=50),
        ),
    ]
